import { assertPreparedModelTask, type PreparedModelTask } from './writing-task.js';
import assert from 'node:assert/strict';
import test from 'node:test';
import { mkdtempSync, readFileSync, rmSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import type { Topic } from '../types.js';
import { roleHash } from '../llm/role-router.js';
import { originalWritingTopic, preparedScriptReceipt, assertPreparedScriptReceipt, assertWritingRequestIdentity, prepareResearchedWriting, writingOutputs, selectedWritingStories, writingNewsletterTarget, writingPersonalizationIdentity, type PreparedScriptReceipt } from './writing-context.js';
import type { WritingPreparationRequest } from './writing-preparation.js';
import type { TopicResearchAdapters } from '../sources/topic-research.js';
import type { EvidenceTopic } from './newsletter-evidence.js';
import { EMPTY_PERSONALIZATION } from '../personalization.js';

const topic = { id: '20260914-sports', kind: 'roundup', headline: 'Sports coverage', stories: [{ headline: 'Harbor match', verifiedClaims: ['The match ended level.'] }] } as Topic;
test('video-only source preparation never inherits a newsletter target or renews an existing output scope', () => {
  const video = { min: 195, max: 220 };
  assert.equal(writingOutputs(), 'video');
  assert.equal(writingOutputs({ outputs: 'edition' }), 'edition');
  assert.equal(writingOutputs(null, 'edition'), 'edition');
  for (const outputs of ['video', 'edition'] as const) {
    assert.equal(writingOutputs({ outputs }, outputs), outputs);
    assert.throws(() => writingOutputs({ outputs }, outputs === 'video' ? 'edition' : 'video'), /Start a new package.*budget cannot be renewed/);
  }
  assert.deepEqual(writingNewsletterTarget('video', 1, video, [900, 1300]), video);
  assert.deepEqual(writingNewsletterTarget('video', 1, video, [900, 1300], 20), { min: 175, max: 200 });
  assert.deepEqual(writingNewsletterTarget('edition', 4, video, [900, 1300]), { min: 900, max: 1300 });
  assert.deepEqual(writingNewsletterTarget('edition', 3, video), { min: 900, max: 1300 });
});

test('one direct source gets scene metadata without inventing verified facts or changing the selected topic', () => {
  for (const kind of ['news', 'repo'] as const) {
    const original: Topic = { id: '20260914-sports', kind, headline: 'Harbor match', angle: 'Sports coverage', primaryUrl: 'https://example.org/sports/match', sourceItems: [], alternates: [], repo: kind === 'repo' ? { fullName: 'league/results', stars: 0, url: 'https://github.com/league/results' } : null };
    const before = structuredClone(original), selected = selectedWritingStories(original);
    assert.deepEqual(original, before);
    assert.equal(selected.length, 1); assert.equal(selected[0]!.primaryUrl, original.primaryUrl);
    assert.equal(selected[0]!.assetRef, 'og-0');
    assert.equal(selected[0]!.verifiedClaims, undefined); assert.equal(selected[0]!.claimEvidence, undefined);
    assert.deepEqual(selectedWritingStories({ ...original, stories: selected }), selected);
    assert.throws(() => selectedWritingStories({ ...original, stories: [...selected, ...selected] }), /exactly its original source/);
    assert.throws(() => selectedWritingStories({ ...original, stories: [{ ...selected[0]!, primaryUrl: 'https://example.org/old-city' }] }), /exactly its original source/);
  }
  const selected = selectedWritingStories(topic);
  assert.deepEqual(selected, topic.stories); selected[0]!.headline = 'Changed copy';
  assert.equal(topic.stories![0]!.headline, 'Harbor match');
  assert.throws(() => selectedWritingStories({ ...topic, stories: [] }), /retain its selected stories/);
});
test('source enrichment retains its original request and rejects unrelated replacement facts', () => {
  const original = structuredClone(topic), prepared = structuredClone(topic);
  prepared.stories![0]!.verifiedClaims!.push('The report lists no injury assessment.');
  const saved = { original, originalHash: roleHash(original), preparedHash: roleHash(prepared) };
  assert.deepEqual(originalWritingTopic(original, saved), original);
  assert.deepEqual(originalWritingTopic(prepared, saved), original);
  assert.throws(() => originalWritingTopic({ ...prepared, headline: 'Old city activities' }, saved), /selected package changed/);
  const changed = structuredClone(saved); changed.original.stories![0]!.verifiedClaims = ['Unrelated replacement.'];
  assert.throws(() => originalWritingTopic(prepared, changed), /selected package changed/);
});

test('completed script reuse requires exact prepared evidence, writer settings and generated bytes', () => {
  const script = { body: [{ voiceover: 'The match ended level.' }] }, writerKey = 'exact model and current settings';
  const receipt = preparedScriptReceipt(topic, writerKey, script);
  assert.doesNotThrow(() => assertPreparedScriptReceipt(receipt, topic, writerKey, script));
  assert.throws(() => assertPreparedScriptReceipt(null, topic, writerKey, script), /not bound/);
  assert.throws(() => assertPreparedScriptReceipt(receipt, { ...topic, headline: 'Changed request' }, writerKey, script), /not bound/);
  assert.throws(() => assertPreparedScriptReceipt(receipt, topic, 'different writer', script), /not bound/);
  assert.throws(() => assertPreparedScriptReceipt(receipt, topic, writerKey, { body: [{ voiceover: 'The home side won.' }] }), /not bound/);
  const old = { version: 1, topicHash: receipt.topicHash, writerKey, scriptHash: receipt.scriptHash };
  assert.throws(() => assertPreparedScriptReceipt(old as unknown as PreparedScriptReceipt, topic, writerKey, script), /not bound/, 'identical content from the old unreviewed contract cannot be reused');
  for (const key of ['sourceSupportVersion', 'fieldSupportVersion', 'scriptReviewVersion'] as const) {
    assert.throws(() => assertPreparedScriptReceipt({ ...receipt, [key]: receipt[key] - 1 }, topic, writerKey, script), /not bound/);
  }
});

test('changing model, settings or cast cannot create a new allowance for the same package', () => {
  const saved = { original: topic, originalHash: roleHash(topic), parentIdentity: roleHash({ settings: 'original' }) };
  assert.doesNotThrow(() => assertWritingRequestIdentity(saved, saved.parentIdentity));
  assert.throws(() => assertWritingRequestIdentity(saved, roleHash({ settings: 'new model or length or cast' })), /cannot reset/);
  assert.throws(() => assertWritingRequestIdentity({ original: topic, originalHash: roleHash(topic) }, saved.parentIdentity), /cannot reset/);
});

test('production research-to-writing bridge preserves Deep length, exact facts and one shared allowance without refetching', async () => {
  const root = mkdtempSync(join(tmpdir(), 'research-writing-'));
  const rich = JSON.parse(readFileSync(new URL('../../examples/fixtures/newsletter-rich-sports-evidence.json', import.meta.url), 'utf8')) as { topics: Array<EvidenceTopic & { sourceText: string }> };
  const request: WritingPreparationRequest = { parent: { root, parentId: 'sports', parentIdentity: roleHash('original sports request'), limits: { totalSeconds: 120, maxPhysicalCalls: 30, maxToolCalls: 24 } }, day: '2026-09-14', briefHash: roleHash('sports'), settingsHash: roleHash('exact writer'), selectedEvidenceHash: roleHash(rich), topics: rich.topics.map(({ sourceText: _, ...item }) => item), targets: { video: { min: 195, max: 220 }, newsletter: { min: 900, max: 1300 } }, fixedVideoWords: 20 };
  const http: string[] = [], tasks: string[] = [];
  const descriptors: PreparedModelTask[] = [];
  const adapters: TopicResearchAdapters = {
    request: async url => {
      http.push(url);
      if (url.includes('bing.com')) {
        const row = rich.topics.find(item => new URL(url).searchParams.get('q')?.includes(item.id))!;
        return new Response(`<a class="title" href="${row.primaryUrl}">Official source</a>`);
      }
      const row = rich.topics.find(item => item.primaryUrl === url)!;
      assert.ok(row, 'No unselected source can be fetched');
      return new Response(`<article>${row.sourceText}</article>`);
    },
    judge: async <T,>(prompt: string, validate: (value: T) => string | null, context: Parameters<TopicResearchAdapters['judge']>[2]) => {
      tasks.push(context.taskId);
      assertPreparedModelTask(context.task); descriptors.push(context.task);
      context.hooks.beforeAttempt!({ provider: 'ollama', model: 'fixture:4b', attempt: 1, rescue: false, promptBytes: Buffer.byteLength(prompt) });
      const value = context.task.capability === 'query-plan' ? { queries: rich.topics.map(item => ({ topicId: item.id, query: `${item.id} official schedule` })) }
        : context.task.capability === 'page-relevance' ? { sourceId: JSON.parse(prompt.split('FETCHED_SOURCE: ')[1]!).id, supported: true, reason: 'The original official source records the planned schedule and its limitations.' }
        : context.task.capability === 'evidence-review' ? (() => {
          const initial = JSON.parse(prompt.split('INITIAL_SELECTION: ')[1]!.split('\n')[0]!);
          return initial;
        })()
        : { selectedIds: JSON.parse(prompt.split('SOURCE_SENTENCES: ')[1]!).map((row: { id: number }) => row.id), requiredIds: [], unsupportedCandidate: [] };
      assert.equal(validate(value as T), null); return value as T;
    },
  };
  try {
    const result = await prepareResearchedWriting(request, adapters);
    assert.equal(result.status, 'ready'); if (result.status !== 'ready') return;
    assert.deepEqual(result.plan.targets, request.targets);
    assert.deepEqual(result.plan.topics.map(item => item.verifiedClaims.join(' ')), rich.topics.map(item => item.sourceText));
    assert.equal(http.length, 6, 'Three searches and three reads; preparation reuses the exact captured artifacts');
    assert.equal(result.parent.toolAttempts, 9); assert.equal(result.parent.physicalAttempts, 10);
    assert.deepEqual(descriptors.map(task => task.capability), ['query-plan', 'page-relevance', 'page-relevance', 'page-relevance', 'evidence-select', 'evidence-review', 'evidence-select', 'evidence-review', 'evidence-select', 'evidence-review']);
    assert.deepEqual(descriptors[0]!.topicIds, request.topics.map(topic => topic.id));
    for (const task of descriptors.slice(1)) assert.equal(task.topicIds.length, 1);
    assert.equal(descriptors[4]!.evidenceHash, descriptors[5]!.evidenceHash, 'initial and independent source selection bind the same full capture');
    const cached = await prepareResearchedWriting(request, adapters);
    assert.equal(cached.status, 'ready'); assert.equal(http.length, 6); assert.equal(tasks.length, 10);
    assert.equal(cached.parent.toolAttempts, 9); assert.equal(cached.parent.physicalAttempts, 10);
  } finally { rmSync(root, { recursive: true, force: true }); }
});


test('image visibility and save timestamps preserve editorial identity while actual writing choices remain bound', () => {
  const initial = { ...EMPTY_PERSONALIZATION, newsletterLength: 'deep' as const, styleNotes: 'Preserve concrete details', updatedAt: '2026-09-14T10:00:00.000Z' };
  const changedImages = { ...initial, newsletterImages: false, updatedAt: '2026-09-15T10:00:00.000Z' };
  assert.deepEqual(writingPersonalizationIdentity(changedImages), writingPersonalizationIdentity(initial));
  const old = { ...initial }; delete (old as Partial<typeof old>).newsletterImages;
  assert.deepEqual(writingPersonalizationIdentity(changedImages, old), old, 'Legacy timestamps retain their old hash slot without comparing the new presentation-save timestamp');
  assert.deepEqual(writingPersonalizationIdentity(changedImages, initial), initial, 'An existing parent that already bound the default image option retains its exact snapshot');
  assert.equal(roleHash(writingPersonalizationIdentity(changedImages, initial)), roleHash(initial), 'Legacy key order is part of the old exact parent hash');
  assert.equal(roleHash(writingPersonalizationIdentity(changedImages, old)), roleHash(old));
  for (const change of [{ newsletterLength: '' as const }, { styleNotes: 'Different prose style' }, { videoLength: 'standard' as const }, { format: 'conversation' as const }, { organization: 'New publisher' }]) {
    assert.notEqual(roleHash(writingPersonalizationIdentity({ ...changedImages, ...change }, old)), roleHash(old));
  }
});
