/** Small local console; credentials remain in this tab's session storage. */
export const controlPage = `<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Content control</title>
<style>@font-face{font-family:Fraunces;src:url(/journey-assets/fraunces.woff2)}@font-face{font-family:Plex;src:url(/journey-assets/ibm-plex-sans.woff2)}h1,h2{font-family:Fraunces,Georgia,serif;font-weight:500}body{font:16px/1.6 Plex,system-ui;max-width:1200px;margin:auto;padding:24px;background:#0B0B14;color:#F4F2FB}h1{margin:0}input,select,button{font:inherit;padding:11px;border:1px solid #49455F;border-radius:6px;background:#13121E;color:inherit}button{cursor:pointer;min-height:44px}dialog::backdrop{background:#0B0B14DD}button:focus-visible,a:focus-visible{outline:3px solid #00C2FF}label{display:inline-grid;gap:4px;margin:12px 8px 12px 0}table{border-collapse:collapse;width:100%;margin:20px 0}th,td{text-align:left;padding:10px;border-bottom:1px solid #49455F}small{color:#ABA6C4}dialog{max-width:min(850px,90vw);background:#13121E;color:#fff;border:1px solid #49455F;border-radius:10px}video{max-width:100%;max-height:55vh}pre{white-space:pre-wrap;max-height:30vh;overflow:auto}#notice{white-space:pre-wrap;color:#00C2FF}.scroll{overflow:auto}.actions{display:flex;gap:8px;flex-wrap:wrap}</style>
<p><a href="/journey" style="color:#00C2FF">← Guided workspace</a></p><h1>Review your private preview.</h1><p>Open a package, watch the video, and read the newsletter before approving its exact contents.</p>
<section id="needsWorkspace" hidden><h2>This page needs your workspace.</h2><p>Your finished preview opens inside your workspace, where you are already signed in. Nothing was lost.</p><p id="accessProblem" role="status"></p><p><a id="returnToWorkspace" href="/journey" style="display:inline-block;padding:11px 19px;border-radius:6px;background:#7C5CFF;color:#fff;text-decoration:none">Return to your workspace</a></p></section>
<details id="developer"><summary>Developer tools</summary><form id="connect"><label>Workspace<input id="workspace" placeholder="legacy or workspace id" value="legacy" pattern="[a-zA-Z0-9_-]+"></label><label>Access token<input id="token" type="password" autocomplete="off" required size="26"></label><button>Connect</button></form></details>
<div id="console" hidden><label>Desk<select id="desk"><option value="">All desks</option></select></label><button id="refresh">Refresh</button><p id="notice" role="status"></p><div class="scroll"><table><thead><tr><th>Package</th><th>Desk / edition</th><th>State</th><th>Delivered / missing</th><th>Review</th></tr></thead><tbody id="rows"></tbody></table></div><details><summary>Analytics snapshot status</summary><pre id="analytics"></pre></details></div>
<dialog id="review"><form method="dialog"><button style="float:right">Close</button></form><h2 id="title"></h2><small id="hash"></small><video id="video" controls></video><details><summary>Topic and script</summary><pre id="package"></pre></details><details><summary>Newsletter artifacts</summary><iframe id="newsletter" sandbox="" title="Exact newsletter" style="width:100%;height:50vh;background:white"></iframe><iframe id="linkedin" sandbox="" title="Exact LinkedIn newsletter" style="width:100%;height:50vh;background:white"></iframe></details><label><input id="reviewed" type="checkbox">I reviewed these exact artifacts</label><div class="actions"><button id="approve">Approve package</button><button id="hold">Hold package</button><label>Retry channel<select id="channel"></select></label><button id="retry">Retry missing delivery</button></div><p id="result" role="status"></p></dialog>
<script>
const el=id=>document.getElementById(id);let state,selected,reviewHash,blobUrl,loading=false,loadedConnection;const connectionKey=()=>el("workspace").value+":"+el("token").value;
// The workspace arrives the same way /journey receives it: workspace in the query, token in the fragment
// (never sent to the server or its log), both moved into this tab's session storage at once.
const givenToken=new URLSearchParams(location.hash.slice(1)).get('token'),givenWorkspace=new URLSearchParams(location.search).get('workspace');
if(givenToken){sessionStorage.setItem('workspace',givenWorkspace||'legacy');sessionStorage.setItem('token',givenToken);history.replaceState(null,'',location.pathname);}
el('workspace').value=sessionStorage.getItem('workspace')||'legacy';el('token').value=sessionStorage.getItem('token')||'';
// Without a workspace this page is one plain action, not an empty table beside a credential form.
function gate(){const connected=Boolean(el('token').value.trim());el('needsWorkspace').hidden=connected;el('console').hidden=!connected;}
async function api(path,options={}){const slug=el('workspace').value.trim();const r=await fetch(path+(slug!=='legacy'?'?workspace='+encodeURIComponent(slug):''),{...options,headers:{authorization:'Bearer '+el('token').value.trim(),...options.headers}});if(!r.ok){const e=new Error((await r.json()).error||('HTTP '+r.status));e.status=r.status;throw e;}return r;}
function cell(row,value){const td=document.createElement('td');td.textContent=value;row.append(td);return td;}
function render(){el('rows').replaceChildren();for(const v of state.videos.filter(v=>!el('desk').value||v.desk===el('desk').value)){const row=document.createElement('tr');cell(row,v.headline);cell(row,(v.desk||'Unassigned')+' / '+v.edition);cell(row,v.status+(v.held?' (held)':'')+(v.uncertain?.length?' (verify delivery: '+v.uncertain.join(', ')+')':''));cell(row,Object.keys(v.posts).join(', ')+' / '+v.missing.join(', '));const b=document.createElement('button');b.textContent='Open';b.onclick=()=>openPackage(v).catch(e=>el('notice').textContent=e.message);cell(row,'').append(b);el('rows').append(row);}}
async function refresh(){try{state=await(await api('/v1/state')).json();const old=el('desk').value;el('desk').replaceChildren(new Option('All desks',''),...Object.keys(state.desks).map(d=>new Option(d,d)));el('desk').value=old;render();const snapshots=state.analytics.snapshots||[];const counts={};for(const s of snapshots)counts[s.platform+' / '+s.status]=(counts[s.platform+' / '+s.status]||0)+1;el('analytics').textContent=JSON.stringify({snapshots:snapshots.length,lastCaptured:snapshots.map(s=>s.capturedAt).sort().at(-1)||null,statuses:counts,attribution:state.attribution},null,2);el('notice').textContent=state.workspace.name+' · '+state.generatedAt;}catch(e){el('notice').textContent=e.message;if(e.status===401||e.status===403){el('accessProblem').textContent='The saved access for this tab is no longer valid ('+e.message+'). Return to your workspace, or enter a current token under Developer tools.';el('needsWorkspace').hidden=false;el('console').hidden=true;el('developer').open=true;}}}
async function openPackage(v){if(loading)return;loading=true;el("approve").disabled=true;el("review").close();selected=undefined;loadedConnection=connectionKey();try{el('title').textContent=v.headline;el('result').textContent='';el('reviewed').checked=false;reviewHash=(await(await api('/v1/packages/'+v.id)).json()).hash;el('hash').textContent='Package SHA-256: '+reviewHash;const parts=[];for(const name of ['topic.json','script.json'])parts.push(name+'\\n'+await(await api('/v1/packages/'+v.id+'/artifact/'+name)).text());el('package').textContent=parts.join('\\n\\n');if(blobUrl)URL.revokeObjectURL(blobUrl);blobUrl=URL.createObjectURL(await(await api('/v1/packages/'+v.id+'/artifact/final.mp4')).blob());el('video').src=blobUrl;for(const [target,name] of [['newsletter','newsletter.html'],['linkedin','newsletter.linkedin.html']]){try{el(target).srcdoc=await(await api('/v1/packages/'+v.id+'/artifact/'+name)).text();}catch(e){if(e.status!==404)throw e;el(target).srcdoc='<p>No newsletter artifact in this package.</p>';}}if((await(await api('/v1/packages/'+v.id)).json()).hash!==reviewHash)throw new Error('Package changed while loading. Reopen it for review.');el('channel').replaceChildren(...v.missing.map(p=>new Option(p,p)));if(connectionKey()!==loadedConnection)throw new Error('Connection changed. Reopen the package.');selected=v;el('approve').disabled=false;el('review').showModal();}catch(e){selected=undefined;el('approve').disabled=true;throw e;}finally{loading=false;}}
async function action(name){try{if(loading||!selected||connectionKey()!==loadedConnection)throw new Error('Reopen the package for the current connection.');if(name==='approve'&&!el('reviewed').checked)throw new Error('Review the displayed package before approving.');const body={expectedHash:reviewHash,reason:'Held from local control console',platform:name==='retry'?el('channel').value:undefined};if(name==='retry'&&!body.platform)throw new Error('No missing channel selected.');el('result').textContent='Running '+name+'…';const receipt=await(await api('/v1/packages/'+selected.id+'/'+name,{method:'POST',headers:{'content-type':'application/json','idempotency-key':crypto.randomUUID()},body:JSON.stringify(body)})).json();el('result').textContent=JSON.stringify(receipt);await refresh();}catch(e){el('result').textContent=e.message;}}
el('connect').onsubmit=e=>{e.preventDefault();sessionStorage.setItem('workspace',el('workspace').value);sessionStorage.setItem('token',el('token').value);gate();refresh();};el('refresh').onclick=refresh;el('desk').onchange=render;for(const a of ['approve','hold','retry'])el(a).onclick=()=>action(a);gate();if(el('token').value)refresh();
</script></html>`;
