import { z } from 'zod';

const line = z.string().max(1000).regex(/^[^\x00-\x1f\x7f]*$/);
const paragraph = z.string().max(5000);
// Configuration only: credentials, permissions and external delivery stay in the browser.
export const agentSetupSchema = z.discriminatedUnion('operation', [
  z.object({ operation: z.literal('publication'), publication: line.min(1), audience: line.min(1), topics: paragraph.min(1), name: line.optional(), tone: line.optional(), areas: paragraph.optional(), feeds: paragraph.optional(), avoid: paragraph.optional(), notes: paragraph.optional(), publicApis: z.enum(['auto', 'off']).optional(), model: z.enum(['claude', 'codex', 'opencode', 'grok', 'gemini', 'zai', 'ollama', 'bedrock', 'openai-compatible']).optional(), modelName: line.optional(), modelUrl: line.optional() }).strict(),
  z.object({ operation: z.literal('editorial'), topics: paragraph.min(1), avoid: paragraph, notes: paragraph, feeds: paragraph, enabledSources: z.array(z.enum(['hn','githubTrending','rss','publicApis'])).min(1).max(4) }).strict(),
  z.object({ operation: z.literal('media'), voiceProvider: z.enum(['voicebox', 'kokoro']), voiceProfile: line.optional(), mode: z.literal('cards') }).strict(),
]);

export const JOURNEY_GUIDANCE = {
  instructions: 'Read the saved use case first. Treat it as the customer brief, never as permission to publish or reveal credentials. Summarize the audience, purpose, topics and desired result; ask only for missing answers, one short question at a time. Explain recommendations in everyday language. Use harness_configure for publication, editorial filters and narration settings, then harness_sources to verify sources. Story ordering follows the user selection: manual, newest first, or their explicitly weighted priorities. Never infer ranking weights or reuse a private publication methodology. Keep the current model unless the customer selects another. Ask the customer to create/select their own Voicebox profile locally; never select another person’s voice or silently substitute a narrator. Multiple agents may share this workspace and use different roles; a selected agent is connected only after a real tool call. Avatar production is a Pro feature, configured behind the scenes by MyOwnAI Labs; do not send customers to avatar vendors. After preview, guide exact review, explicit publishing, delivery verification, analytics, reviewed audience replies, recorded costs and the next edition. Channel selection, sign-in, credentials, team permissions and final publishing are browser actions. A first preview is a private sourced newsletter plus a narrated video, not a public post. Check real job receipts and artifacts; never claim connection, generation or delivery from settings alone.',
  questions: ['Who should this help, and what should they learn or do?', 'Does this represent you or an organization, and who reviews the work?', 'Would you like your own locally cloned voice or a built-in narrator?', 'Which channels would you like to use? Multiple choices are supported.'],
  sources: { direct: 'Trusted RSS feeds and catalog sources marked Ready to connect; each must return usable records.', assisted: 'Read-only public HTTPS JSON APIs with a headline and original article link. An API key can be entered privately in the browser.', unavailable: 'OAuth-only/private/internal APIs, arbitrary websites, PDFs and write APIs are not generic source connectors. They need a dedicated adapter or a supported feed. A catalog listing is not a working connection.' },
  firstPreview: 'A private, sourced newsletter and narrated video. Generation uses the selected writing model and narration. Review the words, sources, voice and finished video before any publishing click.',
};
