import assert from 'node:assert/strict';
import test from 'node:test';
import { createHash } from 'node:crypto';
import { gzipSync } from 'node:zlib';
import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, symlinkSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { downloadOfficial, LLMFIT_ASSETS, setupLlmfit, verifiedTarBinary } from './setup-llmfit.mjs';
const sha=bytes=>createHash('sha256').update(bytes).digest('hex');
function archive(name='llmfit/llmfit',type='0') {const header=Buffer.alloc(512),body=Buffer.from('fake fixture binary');header.write(name);header.write('0000755\0',100);header.write('0000000\0',108);header.write('0000000\0',116);header.write(body.length.toString(8).padStart(11,'0')+'\0',124);header.write('00000000000\0',136);header.fill(32,148,156);header.write(type,156);header.write(header.reduce((s,b)=>s+b,0).toString(8).padStart(6,'0')+'\0 ',148);return gzipSync(Buffer.concat([header,body,Buffer.alloc(512-body.length),Buffer.alloc(1024)]));}
test('archive checksum and header/path/type checks precede writing any executable',()=>{const bytes=archive();assert.equal(verifiedTarBinary(bytes,sha(bytes)).toString(),'fake fixture binary');assert.throws(()=>verifiedTarBinary(bytes,'a'.repeat(64)),/checksum/);for(const [name,type] of [['../llmfit','0'],['/llmfit','0'],['llmfit','2'],['llmfit','1'],['llmfit\\llmfit','0']]){const bad=archive(name,type);assert.throws(()=>verifiedTarBinary(bad,sha(bad)),/Unsafe/);}const missing=archive('README');assert.throws(()=>verifiedTarBinary(missing,sha(missing)),/did not contain/);});
test('download follows only official HTTPS hosts and caps actual response bytes',async()=>{const signal=AbortSignal.timeout(1000),seen=[];const response=await downloadOfficial('https://github.com/AlexsJones/llmfit/releases/download/v1.1.15/test',50,signal,async(url,options)=>{seen.push(url.hostname);assert.equal(options.redirect,'manual');assert.equal(options.signal,signal);return seen.length===1?new Response(null,{status:302,headers:{location:'https://release-assets.githubusercontent.com/fixture'}}):new Response('verified');});assert.equal(response.toString(),'verified');assert.deepEqual(seen,['github.com','release-assets.githubusercontent.com']);let calls=0;await assert.rejects(downloadOfficial('https://github.com/fixture',50,signal,async()=>{calls++;return new Response(null,{status:302,headers:{location:'http://127.0.0.1/private'}});}),/outside the official/);assert.equal(calls,1);let cancelled=false;await assert.rejects(downloadOfficial('https://github.com/fixture',10,signal,async()=>new Response(new ReadableStream({start(controller){controller.enqueue(new Uint8Array(11));},cancel(){cancelled=true;}}))),/byte limit/);assert.equal(cancelled,true);});
test('explicit setup rejects changed published checksum and never overwrites existing tool files',async()=>{const root=mkdtempSync(join(tmpdir(),'llmfit-setup-'));try{let calls=0;await assert.rejects(setupLlmfit(root,{platform:'darwin',arch:'arm64',fetcher:async()=>{calls++;return new Response('a'.repeat(64)+' wrong.tar.gz');}}),/Published.*checksum/);assert.equal(calls,1);const dir=join(root,'workdir/tools/llmfit/v1.1.15');assert.equal(existsSync(dir),false);mkdirSync(dir);writeFileSync(join(dir,'llmfit'),'keep');writeFileSync(join(dir,'provenance.json'),'{}');await assert.rejects(setupLlmfit(root,{platform:'darwin',arch:'arm64'}),/Existing.*do not match/);assert.equal(readFileSync(join(dir,'llmfit'),'utf8'),'keep');await assert.rejects(setupLlmfit(root,{platform:'win32',arch:'x64'}),/Native Windows setup is unsupported in this version/);assert.equal(LLMFIT_ASSETS['darwin/arm64'].sha256,'6207b32a3fa97778a21afed7bbf5f33c569bda35202e04a27b4989880687e6d7');}finally{rmSync(root,{recursive:true,force:true});}});
test('setup refuses a linked project tool path',async()=>{const root=mkdtempSync(join(tmpdir(),'llmfit-linked-')),outside=mkdtempSync(join(tmpdir(),'llmfit-outside-'));try{symlinkSync(outside,join(root,'workdir'),'dir');await assert.rejects(setupLlmfit(root,{platform:'darwin',arch:'arm64'}),/not a regular project directory/);assert.equal(existsSync(join(outside,'tools')),false);}finally{rmSync(root,{recursive:true,force:true});rmSync(outside,{recursive:true,force:true});}});
